/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ActivityPub : ActivityPub type

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityPub {
  #[serde(rename = "@context")]
  context: Option<String>
}

impl ActivityPub {
  /// ActivityPub type
  pub fn new() -> ActivityPub {
    ActivityPub {
      context: None
    }
  }

  pub fn set_context(&mut self, context: String) {
    self.context = Some(context);
  }

  pub fn with_context(mut self, context: String) -> ActivityPub {
    self.context = Some(context);
    self
  }

  pub fn context(&self) -> Option<&String> {
    self.context.as_ref()
  }

  pub fn reset_context(&mut self) {
    self.context = None;
  }

}



