/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CreateOrUpdateSecretOption : CreateOrUpdateSecretOption options when creating or updating secret

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateOrUpdateSecretOption {
  /// Data of the secret to update
  #[serde(rename = "data")]
  data: String
}

impl CreateOrUpdateSecretOption {
  /// CreateOrUpdateSecretOption options when creating or updating secret
  pub fn new(data: String) -> CreateOrUpdateSecretOption {
    CreateOrUpdateSecretOption {
      data: data
    }
  }

  pub fn set_data(&mut self, data: String) {
    self.data = data;
  }

  pub fn with_data(mut self, data: String) -> CreateOrUpdateSecretOption {
    self.data = data;
    self
  }

  pub fn data(&self) -> &String {
    &self.data
  }


}



