/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DismissPullReviewOptions : DismissPullReviewOptions are options to dismiss a pull review

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DismissPullReviewOptions {
  #[serde(rename = "message")]
  message: Option<String>,
  #[serde(rename = "priors")]
  priors: Option<bool>
}

impl DismissPullReviewOptions {
  /// DismissPullReviewOptions are options to dismiss a pull review
  pub fn new() -> DismissPullReviewOptions {
    DismissPullReviewOptions {
      message: None,
      priors: None
    }
  }

  pub fn set_message(&mut self, message: String) {
    self.message = Some(message);
  }

  pub fn with_message(mut self, message: String) -> DismissPullReviewOptions {
    self.message = Some(message);
    self
  }

  pub fn message(&self) -> Option<&String> {
    self.message.as_ref()
  }

  pub fn reset_message(&mut self) {
    self.message = None;
  }

  pub fn set_priors(&mut self, priors: bool) {
    self.priors = Some(priors);
  }

  pub fn with_priors(mut self, priors: bool) -> DismissPullReviewOptions {
    self.priors = Some(priors);
    self
  }

  pub fn priors(&self) -> Option<&bool> {
    self.priors.as_ref()
  }

  pub fn reset_priors(&mut self) {
    self.priors = None;
  }

}



