/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// EditLabelOption : EditLabelOption options for editing a label

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct EditLabelOption {
  #[serde(rename = "color")]
  color: Option<String>,
  #[serde(rename = "description")]
  description: Option<String>,
  #[serde(rename = "exclusive")]
  exclusive: Option<bool>,
  #[serde(rename = "is_archived")]
  is_archived: Option<bool>,
  #[serde(rename = "name")]
  name: Option<String>
}

impl EditLabelOption {
  /// EditLabelOption options for editing a label
  pub fn new() -> EditLabelOption {
    EditLabelOption {
      color: None,
      description: None,
      exclusive: None,
      is_archived: None,
      name: None
    }
  }

  pub fn set_color(&mut self, color: String) {
    self.color = Some(color);
  }

  pub fn with_color(mut self, color: String) -> EditLabelOption {
    self.color = Some(color);
    self
  }

  pub fn color(&self) -> Option<&String> {
    self.color.as_ref()
  }

  pub fn reset_color(&mut self) {
    self.color = None;
  }

  pub fn set_description(&mut self, description: String) {
    self.description = Some(description);
  }

  pub fn with_description(mut self, description: String) -> EditLabelOption {
    self.description = Some(description);
    self
  }

  pub fn description(&self) -> Option<&String> {
    self.description.as_ref()
  }

  pub fn reset_description(&mut self) {
    self.description = None;
  }

  pub fn set_exclusive(&mut self, exclusive: bool) {
    self.exclusive = Some(exclusive);
  }

  pub fn with_exclusive(mut self, exclusive: bool) -> EditLabelOption {
    self.exclusive = Some(exclusive);
    self
  }

  pub fn exclusive(&self) -> Option<&bool> {
    self.exclusive.as_ref()
  }

  pub fn reset_exclusive(&mut self) {
    self.exclusive = None;
  }

  pub fn set_is_archived(&mut self, is_archived: bool) {
    self.is_archived = Some(is_archived);
  }

  pub fn with_is_archived(mut self, is_archived: bool) -> EditLabelOption {
    self.is_archived = Some(is_archived);
    self
  }

  pub fn is_archived(&self) -> Option<&bool> {
    self.is_archived.as_ref()
  }

  pub fn reset_is_archived(&mut self) {
    self.is_archived = None;
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> EditLabelOption {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

}



