/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FilesResponse : FilesResponse contains information about multiple files from a repo

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FilesResponse {
  #[serde(rename = "commit")]
  commit: Option<::models::FileCommitResponse>,
  #[serde(rename = "files")]
  files: Option<Vec<::models::ContentsResponse>>,
  #[serde(rename = "verification")]
  verification: Option<::models::PayloadCommitVerification>
}

impl FilesResponse {
  /// FilesResponse contains information about multiple files from a repo
  pub fn new() -> FilesResponse {
    FilesResponse {
      commit: None,
      files: None,
      verification: None
    }
  }

  pub fn set_commit(&mut self, commit: ::models::FileCommitResponse) {
    self.commit = Some(commit);
  }

  pub fn with_commit(mut self, commit: ::models::FileCommitResponse) -> FilesResponse {
    self.commit = Some(commit);
    self
  }

  pub fn commit(&self) -> Option<&::models::FileCommitResponse> {
    self.commit.as_ref()
  }

  pub fn reset_commit(&mut self) {
    self.commit = None;
  }

  pub fn set_files(&mut self, files: Vec<::models::ContentsResponse>) {
    self.files = Some(files);
  }

  pub fn with_files(mut self, files: Vec<::models::ContentsResponse>) -> FilesResponse {
    self.files = Some(files);
    self
  }

  pub fn files(&self) -> Option<&Vec<::models::ContentsResponse>> {
    self.files.as_ref()
  }

  pub fn reset_files(&mut self) {
    self.files = None;
  }

  pub fn set_verification(&mut self, verification: ::models::PayloadCommitVerification) {
    self.verification = Some(verification);
  }

  pub fn with_verification(mut self, verification: ::models::PayloadCommitVerification) -> FilesResponse {
    self.verification = Some(verification);
    self
  }

  pub fn verification(&self) -> Option<&::models::PayloadCommitVerification> {
    self.verification.as_ref()
  }

  pub fn reset_verification(&mut self) {
    self.verification = None;
  }

}



