/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IssueTemplateLabels {
}

impl IssueTemplateLabels {
  pub fn new() -> IssueTemplateLabels {
    IssueTemplateLabels {
    }
  }

}



