/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// MergePullRequestOption : MergePullRequestForm form for merging Pull Request

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MergePullRequestOption {
  #[serde(rename = "Do")]
  _do: String,
  #[serde(rename = "MergeCommitID")]
  merge_commit_id: Option<String>,
  #[serde(rename = "MergeMessageField")]
  merge_message_field: Option<String>,
  #[serde(rename = "MergeTitleField")]
  merge_title_field: Option<String>,
  #[serde(rename = "delete_branch_after_merge")]
  delete_branch_after_merge: Option<bool>,
  #[serde(rename = "force_merge")]
  force_merge: Option<bool>,
  #[serde(rename = "head_commit_id")]
  head_commit_id: Option<String>,
  #[serde(rename = "merge_when_checks_succeed")]
  merge_when_checks_succeed: Option<bool>
}

impl MergePullRequestOption {
  /// MergePullRequestForm form for merging Pull Request
  pub fn new(_do: String) -> MergePullRequestOption {
    MergePullRequestOption {
      _do: _do,
      merge_commit_id: None,
      merge_message_field: None,
      merge_title_field: None,
      delete_branch_after_merge: None,
      force_merge: None,
      head_commit_id: None,
      merge_when_checks_succeed: None
    }
  }

  pub fn set__do(&mut self, _do: String) {
    self._do = _do;
  }

  pub fn with__do(mut self, _do: String) -> MergePullRequestOption {
    self._do = _do;
    self
  }

  pub fn _do(&self) -> &String {
    &self._do
  }


  pub fn set_merge_commit_id(&mut self, merge_commit_id: String) {
    self.merge_commit_id = Some(merge_commit_id);
  }

  pub fn with_merge_commit_id(mut self, merge_commit_id: String) -> MergePullRequestOption {
    self.merge_commit_id = Some(merge_commit_id);
    self
  }

  pub fn merge_commit_id(&self) -> Option<&String> {
    self.merge_commit_id.as_ref()
  }

  pub fn reset_merge_commit_id(&mut self) {
    self.merge_commit_id = None;
  }

  pub fn set_merge_message_field(&mut self, merge_message_field: String) {
    self.merge_message_field = Some(merge_message_field);
  }

  pub fn with_merge_message_field(mut self, merge_message_field: String) -> MergePullRequestOption {
    self.merge_message_field = Some(merge_message_field);
    self
  }

  pub fn merge_message_field(&self) -> Option<&String> {
    self.merge_message_field.as_ref()
  }

  pub fn reset_merge_message_field(&mut self) {
    self.merge_message_field = None;
  }

  pub fn set_merge_title_field(&mut self, merge_title_field: String) {
    self.merge_title_field = Some(merge_title_field);
  }

  pub fn with_merge_title_field(mut self, merge_title_field: String) -> MergePullRequestOption {
    self.merge_title_field = Some(merge_title_field);
    self
  }

  pub fn merge_title_field(&self) -> Option<&String> {
    self.merge_title_field.as_ref()
  }

  pub fn reset_merge_title_field(&mut self) {
    self.merge_title_field = None;
  }

  pub fn set_delete_branch_after_merge(&mut self, delete_branch_after_merge: bool) {
    self.delete_branch_after_merge = Some(delete_branch_after_merge);
  }

  pub fn with_delete_branch_after_merge(mut self, delete_branch_after_merge: bool) -> MergePullRequestOption {
    self.delete_branch_after_merge = Some(delete_branch_after_merge);
    self
  }

  pub fn delete_branch_after_merge(&self) -> Option<&bool> {
    self.delete_branch_after_merge.as_ref()
  }

  pub fn reset_delete_branch_after_merge(&mut self) {
    self.delete_branch_after_merge = None;
  }

  pub fn set_force_merge(&mut self, force_merge: bool) {
    self.force_merge = Some(force_merge);
  }

  pub fn with_force_merge(mut self, force_merge: bool) -> MergePullRequestOption {
    self.force_merge = Some(force_merge);
    self
  }

  pub fn force_merge(&self) -> Option<&bool> {
    self.force_merge.as_ref()
  }

  pub fn reset_force_merge(&mut self) {
    self.force_merge = None;
  }

  pub fn set_head_commit_id(&mut self, head_commit_id: String) {
    self.head_commit_id = Some(head_commit_id);
  }

  pub fn with_head_commit_id(mut self, head_commit_id: String) -> MergePullRequestOption {
    self.head_commit_id = Some(head_commit_id);
    self
  }

  pub fn head_commit_id(&self) -> Option<&String> {
    self.head_commit_id.as_ref()
  }

  pub fn reset_head_commit_id(&mut self) {
    self.head_commit_id = None;
  }

  pub fn set_merge_when_checks_succeed(&mut self, merge_when_checks_succeed: bool) {
    self.merge_when_checks_succeed = Some(merge_when_checks_succeed);
  }

  pub fn with_merge_when_checks_succeed(mut self, merge_when_checks_succeed: bool) -> MergePullRequestOption {
    self.merge_when_checks_succeed = Some(merge_when_checks_succeed);
    self
  }

  pub fn merge_when_checks_succeed(&self) -> Option<&bool> {
    self.merge_when_checks_succeed.as_ref()
  }

  pub fn reset_merge_when_checks_succeed(&mut self) {
    self.merge_when_checks_succeed = None;
  }

}



