/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RenameUserOption : RenameUserOption options when renaming a user

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RenameUserOption {
  /// New username for this user. This name cannot be in use yet by any other user.
  #[serde(rename = "new_username")]
  new_username: String
}

impl RenameUserOption {
  /// RenameUserOption options when renaming a user
  pub fn new(new_username: String) -> RenameUserOption {
    RenameUserOption {
      new_username: new_username
    }
  }

  pub fn set_new_username(&mut self, new_username: String) {
    self.new_username = new_username;
  }

  pub fn with_new_username(mut self, new_username: String) -> RenameUserOption {
    self.new_username = new_username;
    self
  }

  pub fn new_username(&self) -> &String {
    &self.new_username
  }


}



