/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TransferRepoOption : TransferRepoOption options when transfer a repository's ownership

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransferRepoOption {
  #[serde(rename = "new_owner")]
  new_owner: String,
  /// ID of the team or teams to add to the repository. Teams can only be added to organization-owned repositories.
  #[serde(rename = "team_ids")]
  team_ids: Option<Vec<i64>>
}

impl TransferRepoOption {
  /// TransferRepoOption options when transfer a repository's ownership
  pub fn new(new_owner: String) -> TransferRepoOption {
    TransferRepoOption {
      new_owner: new_owner,
      team_ids: None
    }
  }

  pub fn set_new_owner(&mut self, new_owner: String) {
    self.new_owner = new_owner;
  }

  pub fn with_new_owner(mut self, new_owner: String) -> TransferRepoOption {
    self.new_owner = new_owner;
    self
  }

  pub fn new_owner(&self) -> &String {
    &self.new_owner
  }


  pub fn set_team_ids(&mut self, team_ids: Vec<i64>) {
    self.team_ids = Some(team_ids);
  }

  pub fn with_team_ids(mut self, team_ids: Vec<i64>) -> TransferRepoOption {
    self.team_ids = Some(team_ids);
    self
  }

  pub fn team_ids(&self) -> Option<&Vec<i64>> {
    self.team_ids.as_ref()
  }

  pub fn reset_team_ids(&mut self) {
    self.team_ids = None;
  }

}



