/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// UpdateRepoAvatarOption : UpdateRepoAvatarUserOption options when updating the repo avatar

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UpdateRepoAvatarOption {
  /// image must be base64 encoded
  #[serde(rename = "image")]
  image: Option<String>
}

impl UpdateRepoAvatarOption {
  /// UpdateRepoAvatarUserOption options when updating the repo avatar
  pub fn new() -> UpdateRepoAvatarOption {
    UpdateRepoAvatarOption {
      image: None
    }
  }

  pub fn set_image(&mut self, image: String) {
    self.image = Some(image);
  }

  pub fn with_image(mut self, image: String) -> UpdateRepoAvatarOption {
    self.image = Some(image);
    self
  }

  pub fn image(&self) -> Option<&String> {
    self.image.as_ref()
  }

  pub fn reset_image(&mut self) {
    self.image = None;
  }

}



