/* 
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.21.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// WikiPageMetaData : WikiPageMetaData wiki page meta information

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct WikiPageMetaData {
  #[serde(rename = "html_url")]
  html_url: Option<String>,
  #[serde(rename = "last_commit")]
  last_commit: Option<::models::WikiCommit>,
  #[serde(rename = "sub_url")]
  sub_url: Option<String>,
  #[serde(rename = "title")]
  title: Option<String>
}

impl WikiPageMetaData {
  /// WikiPageMetaData wiki page meta information
  pub fn new() -> WikiPageMetaData {
    WikiPageMetaData {
      html_url: None,
      last_commit: None,
      sub_url: None,
      title: None
    }
  }

  pub fn set_html_url(&mut self, html_url: String) {
    self.html_url = Some(html_url);
  }

  pub fn with_html_url(mut self, html_url: String) -> WikiPageMetaData {
    self.html_url = Some(html_url);
    self
  }

  pub fn html_url(&self) -> Option<&String> {
    self.html_url.as_ref()
  }

  pub fn reset_html_url(&mut self) {
    self.html_url = None;
  }

  pub fn set_last_commit(&mut self, last_commit: ::models::WikiCommit) {
    self.last_commit = Some(last_commit);
  }

  pub fn with_last_commit(mut self, last_commit: ::models::WikiCommit) -> WikiPageMetaData {
    self.last_commit = Some(last_commit);
    self
  }

  pub fn last_commit(&self) -> Option<&::models::WikiCommit> {
    self.last_commit.as_ref()
  }

  pub fn reset_last_commit(&mut self) {
    self.last_commit = None;
  }

  pub fn set_sub_url(&mut self, sub_url: String) {
    self.sub_url = Some(sub_url);
  }

  pub fn with_sub_url(mut self, sub_url: String) -> WikiPageMetaData {
    self.sub_url = Some(sub_url);
    self
  }

  pub fn sub_url(&self) -> Option<&String> {
    self.sub_url.as_ref()
  }

  pub fn reset_sub_url(&mut self) {
    self.sub_url = None;
  }

  pub fn set_title(&mut self, title: String) {
    self.title = Some(title);
  }

  pub fn with_title(mut self, title: String) -> WikiPageMetaData {
    self.title = Some(title);
    self
  }

  pub fn title(&self) -> Option<&String> {
    self.title.as_ref()
  }

  pub fn reset_title(&mut self) {
    self.title = None;
  }

}



